name: BaseExamples

on:
  workflow_dispatch:

jobs:
  run-base-examples:
    uses: ./.github/workflows/examples_build_reusable.yml
    with:
      category: base
      boards_file: .github/examples/boards.json
      examples_file: .github/examples/base_examples.json
