name: LvglExamples

on:
  workflow_dispatch:

jobs:
  run-lvgl-examples:
    uses: ./.github/workflows/examples_build_reusable.yml
    with:
      category: lvgl
      boards_file: .github/examples/boards.json
      examples_file: .github/examples/lvgl_examples.json
