name: RadioExamples

on:
  workflow_dispatch:

jobs:
  run-radio-examples:
    uses: ./.github/workflows/examples_build_reusable.yml
    with:
      category: radio
      boards_file: .github/examples/boards.json
      examples_file: .github/examples/radio_examples.json
